### ISSUE TITLE
Advent Calender Week1

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT/third_robot_pkg#51]
@AriYu @RyodoTanaka 

つくばチャレンジお疲れ様でした．今日明日は休んで下さい^^
今日の反省会の様子からすると，その後すぐ復帰できそうなので早速始めましょう．

Advent Calender までの毎週のマイルストーンをIssueで管理します．
各週，Issueのリストを完遂することに集中して下さい．

下記の作業を，11/11(金)までにお願いします．11/11に進捗報告をお願いします．

※随時更新予定．

## This Week
まずパッケージを移動させて，不要な要素等を掃除してすっきりさせます．
ros_control化やリファクタリングはその後にしましょう．

### Phase 1
- [x] 三号機のOrganization名を確定する． @MoriKen254 
- [x] 三号機のOrganizationを作成する． @MoriKen254 
  - https://github.com/CIR-KIT-Unit03
- [x] 機能種別ごとのリポジトリを作成する． @MoriKen254 

### Phase 2
- [ ] 現行の三号機パッケージを新Organizationに移行する．必要ならリネームする． @AriYu 
  - コミットログも引き継いで移行する．
  - [ ] 三号機用Organization 配下
  - [ ] CIR-KIT 配下
- [ ] ビルドを通す． @AriYu 
- [ ] 実機動作確認．  @AriYu 
- [ ] Gazebo動作確認． @MoriKen254 
- [ ] Travis を通す． @RyodoTanaka 

## Next Week
もし今週のタスクが早く終わったら，着手してもOKです．
何となく挙げているだけなので，やりたいこと・やるべきことがあればそちらから着手して良いです．

- [ ] SteerDriveController リファクタ  @MoriKen254 
- [ ] SteerDriveController rostestコード作成 @MoriKen254 
- [ ] 実機 ros_control化 @AriYu 
- [ ] xacro フォルダ構成を修正 @RyodoTanaka
- [ ] リファクタリング，命名規約統一

このIssueは一週間で閉じます．残ったタスクは次週に持ち越します．

全体の進捗は，別途送ったBravio側のガントチャートで一元的に管理します．
よろしくおねがいします．

**Comment by MoriKen254** [comment]
@AriYu 
タスクリストを更新しました．パッケージの移動，動作確認をお願いします．もし早期に終わったら，実機のros_control化の着手をお願いします．

@RyodoTanaka 
動作確認ができたパッケージからtravisに着手して下さい．講習会で不在と思いますので，お手すきの際にお願いします．無理のない範囲で．
